% base=[pwd(),filesep(),'..',filesep(),'DDE_Biftool_Nov2025',filesep()];
% ddebiftool_path(base,'sym');
  base=[pwd(),filesep(),'..',filesep(),'DDE_Biftool_Nov2025',filesep()];
addpath([base,filesep,'ddebiftool'],...
    [base,filesep,'ddebiftool_extra_psol'],...
    [base,filesep,'ddebiftool_utilities'],...
    [base,filesep,'ddebiftool_extra_rotsym'],...
    [base,filesep,'ddebiftool_extra_nmfm'],...
    [base,filesep,'ddebiftool_extra_symbolic'],...
    [base,filesep,'ddebiftool_coco']);
format compact
format short 
%%
parnames = {'a','r','gamma','d','k','beta','mu_n','h','tau_delay'};
cind = [parnames; num2cell(1:length(parnames))];
in = struct(cind{:});
par([in.a,      in.r,        in.gamma,      in.d,        in.k,      in.beta,   in.mu_n    in.h,   in.tau_delay])=... 
    [0.00,        0.04,          0.13,        0.04,        1.6,           0.065,      0.00,       2,       0 ];
ndim=2;
stst=dde_stst_create('parameter',par,...
    'x',[0.0;0.0])%par(in.k)*(1-(par(in.mu_n)/par(in.a)))]);
%x0=[0;0.5]%zeros(ndim,1);
    parbd={'min_bound',[in.gamma, 0;  in.k,0.01; in.d,0],...
    'max_bound',   [in.gamma, 1;     in.k, 5; in.d,1],...
    'max_step',    [in.gamma, 0.001;   in.k, 0.05; in.d, 0.001; 0,0.05]};
%%
funcs=set_symfuncs(@sym_energy_hopf,'sys_tau',@ () []);
%%
[eq_branch1,suc1]=SetupStst(funcs,...
    'parameter',par,'x',stst.x,...
    'contpar',in.k,'step',0.05,parbd{:});
figure(1)
clf; hold on
eq_branch1=br_contn(funcs,eq_branch1,400);
eq_branch1=br_rvers(eq_branch1);
eq_branch1=br_contn(funcs,eq_branch1,100);
%%
[eq_branch1ref,nunst_st,eq_brbifs,biflocation]=...
    MonitorChange(funcs,eq_branch1,'min_iterations',5);