function varargout=sym_energy_E(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=0;
   return
  case 'npar'
   varargout{1}=6;
   return
  case 'nf'
   varargout{1}=2;
   return
  case 'nx'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=2;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_energy_E_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2] = sym_energy_E_rhs_1_0(in1,in2,in3,in4)
%sym_energy_E_rhs_1_0
%    [OUT_1,OUT_2] = sym_energy_E_rhs_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    05-Jan-2026 00:54:36

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
t2 = in_1_n1.*in_1_n2.*in_2_n3;
out_1 = -t2-in_1_n1.*(-in_2_n2+in_2_n4+in_1_n1.*in_2_n2+in_1_n2.*in_2_n2);
if nargout > 1
    out_2 = t2-in_1_n2.*(-in_2_n1+in_2_n5+in_1_n1.*in_2_n1+in_1_n2.*in_2_n1);
end
end


function [out_1,out_2] = sym_energy_E_rhs_1_1(in1,in2,in3,in4)
%sym_energy_E_rhs_1_1
%    [OUT_1,OUT_2] = sym_energy_E_rhs_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    05-Jan-2026 00:54:36

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
t2 = in_1_n1.*in_1_n2.*in_4_n3;
t3 = in_1_n1.*in_2_n3.*in_3_n2;
t4 = in_1_n2.*in_2_n3.*in_3_n1;
out_1 = -t2-t3-t4-in_1_n1.*(-in_4_n2+in_4_n4+in_1_n1.*in_4_n2+in_2_n2.*in_3_n1+in_1_n2.*in_4_n2+in_2_n2.*in_3_n2)-in_3_n1.*(-in_2_n2+in_2_n4+in_1_n1.*in_2_n2+in_1_n2.*in_2_n2);
if nargout > 1
    out_2 = t2+t3+t4-in_1_n2.*(-in_4_n1+in_4_n5+in_1_n1.*in_4_n1+in_2_n1.*in_3_n1+in_1_n2.*in_4_n1+in_2_n1.*in_3_n2)-in_3_n2.*(-in_2_n1+in_2_n5+in_1_n1.*in_2_n1+in_1_n2.*in_2_n1);
end
end


function [out_1,out_2] = sym_energy_E_rhs_1_2(in1,in2,in3,in4)
%sym_energy_E_rhs_1_2
%    [OUT_1,OUT_2] = sym_energy_E_rhs_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    05-Jan-2026 00:54:36

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
t2 = in_1_n1.*in_3_n2.*in_4_n3.*2.0;
t3 = in_1_n2.*in_3_n1.*in_4_n3.*2.0;
t4 = in_2_n3.*in_3_n1.*in_3_n2.*2.0;
out_1 = -t2-t3-t4-in_3_n1.*(-in_4_n2+in_4_n4+in_1_n1.*in_4_n2+in_2_n2.*in_3_n1+in_1_n2.*in_4_n2+in_2_n2.*in_3_n2).*2.0-in_1_n1.*(in_3_n1.*in_4_n2.*2.0+in_3_n2.*in_4_n2.*2.0);
if nargout > 1
    out_2 = t2+t3+t4-in_3_n2.*(-in_4_n1+in_4_n5+in_1_n1.*in_4_n1+in_2_n1.*in_3_n1+in_1_n2.*in_4_n1+in_2_n1.*in_3_n2).*2.0-in_1_n2.*(in_3_n1.*in_4_n1.*2.0+in_3_n2.*in_4_n1.*2.0);
end
end

