function varargout=sym_energy_hopf(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=0;
   return
  case 'npar'
   varargout{1}=9;
   return
  case 'nf'
   varargout{1}=2;
   return
  case 'nx'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=2;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_energy_hopf_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2] = sym_energy_hopf_rhs_1_0(in1,in2,in3,in4)
%SYM_ENERGY_HOPF_RHS_1_0
%    [OUT_1,OUT_2] = SYM_ENERGY_HOPF_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 10:46:12

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
t2 = in_1_n1.*in_2_n8;
t3 = t2+1.0;
t4 = 1.0./t3;
out_1 = -in_1_n1.*in_2_n7-in_1_n1.*in_2_n2.*(in_1_n1./in_2_n5-1.0)-in_1_n1.*in_1_n2.*in_2_n6.*t4;
if nargout > 1
    out_2 = -in_1_n2.*(in_2_n4-in_1_n1.*in_2_n3.*t4)-in_1_n2.^2.*in_2_n1;
end
end


function [out_1,out_2] = sym_energy_hopf_rhs_1_1(in1,in2,in3,in4)
%SYM_ENERGY_HOPF_RHS_1_1
%    [OUT_1,OUT_2] = SYM_ENERGY_HOPF_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 10:46:12

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_2_n7 = in2(:,7);
in_2_n8 = in2(:,8);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
t2 = in_1_n1.*in_2_n8;
t3 = in_1_n1.*in_4_n8;
t4 = in_2_n8.*in_3_n1;
t5 = 1.0./in_2_n5;
t6 = t2+1.0;
t7 = in_1_n1.*t5;
t8 = t3+t4;
t9 = 1.0./t6;
t11 = t7-1.0;
t10 = t9.^2;
out_1 = -in_1_n1.*in_4_n7-in_2_n7.*in_3_n1-in_1_n1.*in_2_n2.*(in_3_n1.*t5-in_4_n5.*t5.*t7)-in_1_n1.*in_4_n2.*t11-in_2_n2.*in_3_n1.*t11-in_1_n1.*in_1_n2.*in_4_n6.*t9-in_1_n1.*in_2_n6.*in_3_n2.*t9-in_1_n2.*in_2_n6.*in_3_n1.*t9+in_1_n1.*in_1_n2.*in_2_n6.*t8.*t10;
if nargout > 1
    out_2 = -in_3_n2.*(in_2_n4-in_1_n1.*in_2_n3.*t9)-in_1_n2.^2.*in_4_n1-in_1_n2.*(in_4_n4-in_1_n1.*in_4_n3.*t9-in_2_n3.*in_3_n1.*t9+in_1_n1.*in_2_n3.*t8.*t10)-in_1_n2.*in_2_n1.*in_3_n2.*2.0;
end
end


function [out_1,out_2] = sym_energy_hopf_rhs_1_2(in1,in2,in3,in4)
%SYM_ENERGY_HOPF_RHS_1_2
%    [OUT_1,OUT_2] = SYM_ENERGY_HOPF_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 10:46:13

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_2_n8 = in2(:,8);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
in_4_n7 = in4(:,7);
in_4_n8 = in4(:,8);
t2 = in_1_n1.*in_2_n8;
t3 = in_1_n1.*in_4_n8;
t4 = in_2_n8.*in_3_n1;
t5 = 1.0./in_2_n5;
t6 = t5.^2;
t7 = t2+1.0;
t8 = in_3_n1.*t5;
t9 = t3+t4;
t10 = in_1_n1.*in_4_n5.*t6;
t11 = 1.0./t7;
t14 = t9.^2;
t12 = t11.^2;
t13 = t11.^3;
t15 = -t10;
t16 = t8+t15;
out_1 = in_3_n1.*in_4_n7.*-2.0-in_1_n1.*in_2_n2.*(in_1_n1.*in_4_n5.^2.*t5.^3.*2.0-in_3_n1.*in_4_n5.*t6.*2.0)-in_1_n1.*in_4_n2.*t16.*2.0-in_2_n2.*in_3_n1.*t16.*2.0-in_3_n1.*in_4_n2.*(in_1_n1.*t5-1.0).*2.0-in_1_n1.*in_3_n2.*in_4_n6.*t11.*2.0-in_1_n2.*in_3_n1.*in_4_n6.*t11.*2.0-in_2_n6.*in_3_n1.*in_3_n2.*t11.*2.0-in_1_n1.*in_1_n2.*in_2_n6.*t13.*t14.*2.0+in_1_n2.*in_2_n6.*in_3_n1.*t3.*t12.*2.0+in_1_n1.*in_1_n2.*in_4_n6.*t9.*t12.*2.0+in_1_n1.*in_2_n6.*in_3_n2.*t9.*t12.*2.0+in_1_n2.*in_2_n6.*in_3_n1.*t9.*t12.*2.0;
if nargout > 1
    out_2 = -in_1_n2.*(in_3_n1.*in_4_n3.*t11.*-2.0-in_1_n1.*in_2_n3.*t13.*t14.*2.0+in_2_n3.*in_3_n1.*t3.*t12.*2.0+in_1_n1.*in_4_n3.*t9.*t12.*2.0+in_2_n3.*in_3_n1.*t9.*t12.*2.0)-in_2_n1.*in_3_n2.^2.*2.0-in_3_n2.*(in_4_n4-in_1_n1.*in_4_n3.*t11-in_2_n3.*in_3_n1.*t11+in_1_n1.*in_2_n3.*t9.*t12).*2.0-in_1_n2.*in_3_n2.*in_4_n1.*4.0;
end
end

