function varargout=sym_energy_E_version2(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'npar'
   varargout{1}=7;
   return
  case 'nf'
   varargout{1}=2;
   return
  case 'nx'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=2;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1  2  2];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_energy_E_version2_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2] = sym_energy_E_version2_rhs_1_0(in1,in2,in3,in4)
%sym_energy_E_version2_rhs_1_0
%    [OUT_1,OUT_2] = sym_energy_E_version2_rhs_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 09:42:27

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
t2 = in_1_n1.*in_1_n4.*in_2_n3;
t3 = 1.0./in_2_n6;
out_1 = -t2-in_1_n1.*(in_2_n4+in_2_n2.*(t3.*(in_1_n1+in_1_n4)-1.0));
if nargout > 1
    out_2 = t2-in_1_n2.*(in_2_n5+in_2_n1.*(t3.*(in_1_n1+in_1_n2)-1.0));
end
end


function [out_1,out_2] = sym_energy_E_version2_rhs_1_1(in1,in2,in3,in4)
%sym_energy_E_version2_rhs_1_1
%    [OUT_1,OUT_2] = sym_energy_E_version2_rhs_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 09:42:27

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
t2 = in_1_n1+in_1_n2;
t3 = in_1_n1+in_1_n4;
t4 = in_1_n1.*in_1_n4.*in_4_n3;
t5 = in_1_n1.*in_2_n3.*in_3_n4;
t6 = in_1_n4.*in_2_n3.*in_3_n1;
t7 = 1.0./in_2_n6;
t8 = t7.^2;
t9 = t2.*t7;
t10 = t3.*t7;
t11 = t9-1.0;
t12 = t10-1.0;
out_1 = -t4-t5-t6-in_1_n1.*(in_4_n4+in_4_n2.*t12+in_2_n2.*(t7.*(in_3_n1+in_3_n4)-in_4_n6.*t3.*t8))-in_3_n1.*(in_2_n4+in_2_n2.*t12);
if nargout > 1
    out_2 = t4+t5+t6-in_1_n2.*(in_4_n5+in_4_n1.*t11+in_2_n1.*(t7.*(in_3_n1+in_3_n2)-in_4_n6.*t2.*t8))-in_3_n2.*(in_2_n5+in_2_n1.*t11);
end
end


function [out_1,out_2] = sym_energy_E_version2_rhs_1_2(in1,in2,in3,in4)
%sym_energy_E_version2_rhs_1_2
%    [OUT_1,OUT_2] = sym_energy_E_version2_rhs_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 09:42:28

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_1_n4 = in1(:,4);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n6 = in2(:,6);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_3_n4 = in3(:,4);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n6 = in4(:,6);
t2 = in_1_n1+in_1_n2;
t3 = in_1_n1+in_1_n4;
t4 = in_3_n1+in_3_n2;
t5 = in_3_n1+in_3_n4;
t6 = in_4_n6.^2;
t7 = 1.0./in_2_n6;
t10 = in_1_n1.*in_3_n4.*in_4_n3.*2.0;
t11 = in_1_n4.*in_3_n1.*in_4_n3.*2.0;
t12 = in_2_n3.*in_3_n1.*in_3_n4.*2.0;
t8 = t7.^2;
t9 = t7.^3;
t13 = t4.*t7;
t14 = t5.*t7;
t15 = in_4_n6.*t2.*t8;
t16 = in_4_n6.*t3.*t8;
t17 = -t15;
t18 = -t16;
t19 = t13+t17;
t20 = t14+t18;
out_1 = -t10-t11-t12-in_3_n1.*(in_4_n4+in_2_n2.*t20+in_4_n2.*(t3.*t7-1.0)).*2.0-in_1_n1.*(in_4_n2.*t20.*2.0-in_2_n2.*(in_4_n6.*t5.*t8.*2.0-t3.*t6.*t9.*2.0));
if nargout > 1
    out_2 = t10+t11+t12-in_3_n2.*(in_4_n5+in_2_n1.*t19+in_4_n1.*(t2.*t7-1.0)).*2.0-in_1_n2.*(in_4_n1.*t19.*2.0-in_2_n1.*(in_4_n6.*t4.*t8.*2.0-t2.*t6.*t9.*2.0));
end
end

