function varargout=sym_energy(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=0;
   return
  case 'npar'
   varargout{1}=8;
   return
  case 'nf'
   varargout{1}=2;
   return
  case 'nx'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=2;
   return
  case 'iscollected'
   varargout{1}=0;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
  case 'sys_tau_seq'
   varargout{1}={};
   return
  case 'sys_tau_in'
   varargout{1}=[];
   return
  case 'xpattern'
   varargout{1}=[1  1  2  1];
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_energy_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out_1,out_2] = sym_energy_rhs_1_0(in1,in2,in3,in4)
%SYM_ENERGY_RHS_1_0
%    [OUT_1,OUT_2] = SYM_ENERGY_RHS_1_0(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 09:37:25

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n1 = in2(:,1);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
t2 = in_1_n1.*in_1_n2.*in_2_n3;
out_1 = in_2_n1-t2-in_1_n1.*in_2_n2-in_1_n1.^2.*in_2_n7;
if nargout > 1
    out_2 = t2-in_1_n2.*in_2_n4.*(in_1_n2./in_2_n5-1.0);
end
end


function [out_1,out_2] = sym_energy_rhs_1_1(in1,in2,in3,in4)
%SYM_ENERGY_RHS_1_1
%    [OUT_1,OUT_2] = SYM_ENERGY_RHS_1_1(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 09:37:25

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n2 = in2(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n1 = in4(:,1);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n7 = in4(:,7);
t2 = in_1_n1.*in_1_n2.*in_4_n3;
t3 = in_1_n1.*in_2_n3.*in_3_n2;
t4 = in_1_n2.*in_2_n3.*in_3_n1;
out_1 = in_4_n1-t2-t3-t4-in_1_n1.*in_4_n2-in_2_n2.*in_3_n1-in_1_n1.^2.*in_4_n7-in_1_n1.*in_2_n7.*in_3_n1.*2.0;
if nargout > 1
    t5 = 1.0./in_2_n5;
    t6 = in_1_n2.*t5;
    t7 = t6-1.0;
    out_2 = t2+t3+t4-in_1_n2.*in_2_n4.*(in_3_n2.*t5-in_4_n5.*t5.*t6)-in_1_n2.*in_4_n4.*t7-in_2_n4.*in_3_n2.*t7;
end
end


function [out_1,out_2] = sym_energy_rhs_1_2(in1,in2,in3,in4)
%SYM_ENERGY_RHS_1_2
%    [OUT_1,OUT_2] = SYM_ENERGY_RHS_1_2(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jan-2026 09:37:26

in_1_n1 = in1(:,1);
in_1_n2 = in1(:,2);
in_2_n3 = in2(:,3);
in_2_n4 = in2(:,4);
in_2_n5 = in2(:,5);
in_2_n7 = in2(:,7);
in_3_n1 = in3(:,1);
in_3_n2 = in3(:,2);
in_4_n2 = in4(:,2);
in_4_n3 = in4(:,3);
in_4_n4 = in4(:,4);
in_4_n5 = in4(:,5);
in_4_n7 = in4(:,7);
t2 = 1.0./in_2_n5;
t4 = in_1_n1.*in_3_n2.*in_4_n3.*2.0;
t5 = in_1_n2.*in_3_n1.*in_4_n3.*2.0;
t6 = in_2_n3.*in_3_n1.*in_3_n2.*2.0;
out_1 = -t4-t5-t6-in_3_n1.*in_4_n2.*2.0-in_2_n7.*in_3_n1.^2.*2.0-in_1_n1.*in_3_n1.*in_4_n7.*4.0;
if nargout > 1
    t3 = t2.^2;
    t7 = in_3_n2.*t2;
    t8 = in_1_n2.*in_4_n5.*t3;
    t9 = -t8;
    t10 = t7+t9;
    out_2 = t4+t5+t6-in_1_n2.*in_2_n4.*(in_1_n2.*in_4_n5.^2.*t2.^3.*2.0-in_3_n2.*in_4_n5.*t3.*2.0)-in_1_n2.*in_4_n4.*t10.*2.0-in_2_n4.*in_3_n2.*t10.*2.0-in_3_n2.*in_4_n4.*(in_1_n2.*t2-1.0).*2.0;
end
end

